// ─────────────────────────────────────────────────────────────────────────────
// Phase 6 — Export & Sharing  (additions to export.js)
// ─────────────────────────────────────────────────────────────────────────────
// Covers:
//   6.3 — Code: p5.js sketch, GLSL Sandbox, ShaderToy paste format
//   6.1 B — Export preview thumbnail
// ─────────────────────────────────────────────────────────────────────────────

import * as THREE from 'three';
import { state } from '../core/state.js';
import { VERT } from '../gl/renderer.js';
import { toast } from '../io/actions.js';

/** Render one offscreen frame at w×h and return the raw ImageData */
function _renderOffscreen(w, h, { alpha = false } = {}) {
  const offCanvas = document.createElement('canvas');
  offCanvas.width = w;
  offCanvas.height = h;

  const offRenderer = new THREE.WebGLRenderer({
    canvas: offCanvas,
    antialias: true,
    alpha,
    preserveDrawingBuffer: true,
  });
  offRenderer.setPixelRatio(1);
  offRenderer.setSize(w, h, false);

  const offMat = new THREE.ShaderMaterial({
    vertexShader: VERT,
    fragmentShader: state.mat3.fragmentShader,
    uniforms: {
      ...state.mat3.uniforms,
      iResolution: { value: new THREE.Vector3(w, h, 1) },
    },
    transparent: alpha,
  });

  const offScene = new THREE.Scene();
  const offCam = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
  const offMesh = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), offMat);
  offScene.add(offMesh);
  offRenderer.render(offScene, offCam);

  const gl = offRenderer.getContext();
  const buf = new Uint8Array(w * h * 4);
  gl.readPixels(0, 0, w, h, gl.RGBA, gl.UNSIGNED_BYTE, buf);

  // Flip Y (WebGL origin bottom-left → image top-left)
  const flipped = new Uint8ClampedArray(w * h * 4);
  for (let row = 0; row < h; row++) {
    const src = (h - 1 - row) * w * 4;
    flipped.set(buf.subarray(src, src + w * 4), row * w * 4);
  }

  offMesh.geometry.dispose();
  offMat.dispose();
  offRenderer.dispose();

  return new ImageData(flipped, w, h);
}

function _triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ═════════════════════════════════════════════════════════════════════════════
// §6.3  CODE / PROJECT EXPORT
// ═════════════════════════════════════════════════════════════════════════════

// ── 6.3 A — p5.js sketch ─────────────────────────────────────────────────────

export function exportP5Sketch() {
  const code = state.editor?.getValue() ?? '';

  const sketch = `// p5.js GLSL sketch — generated by Sliders GL
// Paste this into https://editor.p5js.org/

let shaderProg;

const VERT = \`
attribute vec3 aPosition;
void main() {
  gl_Position = vec4(aPosition * 2.0 - 1.0, 1.0);
}
\`;

const FRAG = \`
precision highp float;
uniform vec3 iResolution;
uniform float iTime;
uniform float iTimeDelta;
uniform int iFrame;
uniform vec4 iMouse;

${code}

void main() {
  vec4 col = vec4(0.0);
  mainImage(col, gl_FragCoord.xy);
  gl_FragColor = clamp(col, 0.0, 1.0);
}
\`;

function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
  shaderProg = createShader(VERT, FRAG);
  shader(shaderProg);
  noStroke();
}

function draw() {
  shaderProg.setUniform('iResolution', [width, height, 1.0]);
  shaderProg.setUniform('iTime', millis() / 1000.0);
  shaderProg.setUniform('iTimeDelta', deltaTime / 1000.0);
  shaderProg.setUniform('iFrame', frameCount);
  shaderProg.setUniform('iMouse', [mouseX, height - mouseY, mouseIsPressed ? 1.0 : 0.0, 0.0]);
  rect(-width / 2, -height / 2, width, height);
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}
`;

  const blob = new Blob([sketch], { type: 'text/javascript' });
  _triggerDownload(blob, 'shader-p5js.js');
  toast('p5.js sketch exported', 'ok');
}

// ── 6.3 B — GLSL Sandbox compatible ──────────────────────────────────────────

export function exportGLSLSandbox() {
  const raw = state.editor?.getValue() ?? '';

  // GLSL Sandbox expects gl_FragCoord-based void main(), uniform time & resolution
  // Wrap mainImage convention into a compatible entry point
  const body = `precision mediump float;

uniform float time;
uniform vec2 mouse;
uniform vec2 resolution;

// ── Original shader ──────────────────────────────────────────────────────────
${raw}
// ────────────────────────────────────────────────────────────────────────────

void main(void) {
  // Map GLSL Sandbox uniforms → ShaderToy convention
  vec3 iResolution = vec3(resolution, 1.0);
  float iTime      = time;
  vec4  iMouse     = vec4(mouse * resolution, 0.0, 0.0);

  vec4 color = vec4(0.0, 0.0, 0.0, 1.0);
  mainImage(color, gl_FragCoord.xy);
  gl_FragColor = clamp(color, 0.0, 1.0);
}
`;

  const blob = new Blob([body], { type: 'text/plain' });
  _triggerDownload(blob, 'shader-glslsandbox.glsl');
  toast('GLSL Sandbox shader exported', 'ok');
}

// ── 6.3 C — ShaderToy paste format ───────────────────────────────────────────

export function exportShaderToyFormat() {
  const raw = state.editor?.getValue() ?? '';

  // ShaderToy expects a file containing only the mainImage function body,
  // with no void main() and no uniform declarations (they are injected by ST).
  // We strip any duplicate uniform declarations the user may have in their shader.
  let cleaned = raw;

  // Remove uniform declarations for ShaderToy builtins (user may have added them)
  const builtinUniforms = [
    'iResolution',
    'iTime',
    'iTimeDelta',
    'iFrame',
    'iMouse',
    'iDate',
    'iSampleRate',
    'iChannel0',
    'iChannel1',
    'iChannel2',
    'iChannel3',
    'iChannelResolution',
  ];
  const uniformRegex = new RegExp(
    `^\\s*uniform\\s+\\S+\\s+(${builtinUniforms.join('|')})\\s*(?:\\[\\d+\\])?\\s*;\\s*$`,
    'gm',
  );
  cleaned = cleaned.replace(uniformRegex, '');

  // Remove precision qualifiers (ST injects them)
  cleaned = cleaned.replace(/^\s*precision\s+(highp|mediump|lowp)\s+\w+\s*;\s*$/gm, '');

  // Trim leading blank lines
  cleaned = cleaned.replace(/^\n+/, '');

  const header = `// ── Exported from Sliders GL — paste into ShaderToy Image tab ─────────────────────
// ShaderToy: https://www.shadertoy.com/new
// Uniforms (iTime, iResolution, iMouse, iFrame, iChannel0–3) are provided by ShaderToy.
// ─────────────────────────────────────────────────────────────────────────────

`;

  const blob = new Blob([header + cleaned], { type: 'text/plain' });
  _triggerDownload(blob, 'shader-shadertoy.glsl');
  toast('ShaderToy format exported', 'ok');
}

// ═════════════════════════════════════════════════════════════════════════════
// §6.1  Export preview
// ═════════════════════════════════════════════════════════════════════════════

// ── 6.1 B — Export preview (thumbnail of first frame before starting) ─────────

/**
 * Render and display a small thumbnail preview of the first frame
 * in the export dialog, so users can verify the output before committing.
 */
export async function renderExportPreview(containerId, resVal) {
  const container = document.getElementById(containerId);
  if (!container) return;

  const [w, h] = (resVal || '320x180').split('x').map(Number);
  // Render at a small preview resolution for speed
  const pw = Math.min(w, 320);
  const ph = Math.round(pw * (h / w));

  container.innerHTML = '<div style="font-size:10px;color:var(--prose-lo);font-family:var(--font-mono)">Rendering preview…</div>';

  await new Promise(r => setTimeout(r, 16));

  try {
    const imgData = _renderOffscreen(pw, ph);
    const canvas = document.createElement('canvas');
    canvas.width = pw;
    canvas.height = ph;
    canvas.getContext('2d').putImageData(imgData, 0, 0);

    const dataUrl = canvas.toDataURL('image/jpeg', 0.82);
    container.innerHTML = `
      <img src="${dataUrl}" alt="Export preview"
        style="width:100%;border-radius:6px;border:1px solid var(--b1);display:block"
        aria-label="Preview of frame to be exported">
      <div style="font-size:9px;color:var(--prose-lo);font-family:var(--font-mono);margin-top:3px;text-align:center">
        Preview — ${pw}×${ph}
      </div>`;
  } catch (e) {
    container.innerHTML = `<div style="font-size:10px;color:var(--spark-hot);font-family:var(--font-mono)">Preview failed: ${e.message}</div>`;
  }
}

