; =============================================================================
; Z-GL — NSIS Installer Hooks
; File   : src-tauri/installer/hooks.nsh
; Purpose: Branded installer — splash screen, custom install path,
;          Start Menu entry, Desktop shortcut.
;
; This file is referenced via tauri.conf.json  →  bundle.windows.nsis.installerHooks
; Tauri injects it with !include at the top of the generated NSIS script,
; so all NSIS symbols ($INSTDIR, $SMPROGRAMS, etc.) are already defined.
; =============================================================================

; ── Splash screen ────────────────────────────────────────────────────────────
; Shown for ~2 s before the first installer page.
; The BMP (494 × 312, 24-bit) is generated by scripts/gen-installer-assets.js.
!include "WinMessages.nsh"

Function ShowSplash
  ; Load the splash bitmap from the installer's own directory.
  ; $PLUGINSDIR is a temp folder created by NSIS at installer start.
  InitPluginsDir
  File /oname=$PLUGINSDIR\splash.bmp "${__FILEDIR__}\splash.bmp"

  ; advsplash plugin: show for 2000 ms, fade-out 400 ms, no key-dismiss.
  advsplash::show 2000 400 0 -1 $PLUGINSDIR\splash

  Pop $0   ; result (ignored)
FunctionEnd

; Hook into the NSIS .onInit callback to display the splash before any UI.
Function .onInit
  Call ShowSplash
FunctionEnd

; ── Custom install path ───────────────────────────────────────────────────────
; Override Tauri's default install directory so the app lands in:
;   %LOCALAPPDATA%\ZGL\Z-GL   (per-user install, no UAC required)
;
; We only set it when the user has NOT yet chosen a path
; (i.e. $INSTDIR still equals the Tauri default).

!define ZGL_DEFAULT_INSTDIR "$LOCALAPPDATA\ZGL\Z-GL"

Function OverrideInstDir
  ; Only override when no explicit /D= was passed on the command-line.
  ${If} $INSTDIR == ""
    StrCpy $INSTDIR "${ZGL_DEFAULT_INSTDIR}"
  ${EndIf}
FunctionEnd

; Call the override as early as possible (before the directory page renders).
!insertmacro MUI_FUNCTION_GUIINIT OverrideInstDir

; ── Start Menu shortcut ───────────────────────────────────────────────────────
; Creates:  %APPDATA%\Microsoft\Windows\Start Menu\Programs\Z-GL\Z-GL Shader Editor.lnk

Function CreateStartMenuShortcut
  CreateDirectory "$SMPROGRAMS\Z-GL"
  CreateShortcut  "$SMPROGRAMS\Z-GL\Z-GL Shader Editor.lnk" \
                  "$INSTDIR\Z-GL.exe" \
                  "" \
                  "$INSTDIR\Z-GL.exe" 0 \
                  SW_SHOWNORMAL \
                  "" \
                  "Open the Z-GL real-time shader editor"
FunctionEnd

; Tauri calls the Section named "MainSection" — hook into post-install.
; We use the standard NSIS callback for post-section work.
Function .onInstSuccess
  Call CreateStartMenuShortcut
FunctionEnd

; ── Desktop shortcut ─────────────────────────────────────────────────────────
; Creates:  %USERPROFILE%\Desktop\Z-GL Shader Editor.lnk
; Respects the "Create Desktop Shortcut" checkbox on the installer Options page.
; (tauri.conf.json already sets createDesktopShortcut:true which generates
;  the checkbox; this hook ensures consistent icon + description.)

Function CreateDesktopShortcut
  CreateShortcut "$DESKTOP\Z-GL Shader Editor.lnk" \
                 "$INSTDIR\Z-GL.exe" \
                 "" \
                 "$INSTDIR\Z-GL.exe" 0 \
                 SW_SHOWNORMAL \
                 "" \
                 "Z-GL — Real-time GLSL / WebGPU shader editor"
FunctionEnd

Section "Desktop Shortcut" SEC_DESKTOP
  SectionIn RO   ; selected by default, but user can uncheck
  Call CreateDesktopShortcut
SectionEnd
